Iterate over nodes and templates using nodelist
When iterating over Template and Node objects directly, nodes may fail with an
exception such as:
TypeError: 'TextNode' object is not iterable
This is due to iterating over nodes being unsupported in Django, as noted in
https://code.djangoproject.com/ticket/7430
To avoid this error, explicitly iterate over the nodelist attribute, rather
than relying on __iter__.